[build]
base    = "site/"
publish = "site/generated"
command = "hugo --gc --minify --destination generated"

[context.production.environment]
HUGO_VERSION = "0.53"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
