baseURL = "https://dianeandroyce.com/"
languageCode = "en-us"
title = "Diane to be a Remer"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/colors.css","css/header.css","css/home.css","css/when.css","css/answers.css","css/where.css","css/who.css"]
  
  [params.navigation]
    brand = "#DianeToBeARemer"
    services = "when"
    about = "where"
    testimonials = "answers"
    contact = "who"

  [params.hero]
    title = "Diane to be a Remer!"
    subtitle = 'A union of <a href="#who">Diane Tran</a> and <a href="#who">Royce Remer</a>'
 
  [params.services]
    enable = true
    title = "When"
    date = "June 28th, 2019"

    [[params.services.item]]
      icon = "icon-sun"
      time = "3:00 PM"
      title = "Doors open"
      description = "Walk the grounds and enjoy yourself."
      
    [[params.services.item]]
      icon = "icon-bell2"
      time = "3:15 PM"
      title = "Ceremony"
      description = "A short procession and witnessing of our vows."

    [[params.services.item]]
      icon = "icon-camera2"
      time = "4:00 PM"
      title = "Photos"
      description = 'All the permutations of guest photos. Games and drinks too.'

    [[params.services.item]]
      icon = "icon-heart2"
      time = "5:45 PM"
      title = "Dinner"
      description = 'Dinner is served. <a href="#menu">Menu here</a>.'

    [[params.services.item]]
      icon = "icon-microphone"
      time = "6:00 PM"
      title = "Toasts"
      description = "People extol Diane's grace and fine taste."

    [[params.services.item]]
      icon = "icon-pie-graph"
      time = "7:30 PM"
      title = "Cake"
      description = "People take bites out of Diane's cake."

    [[params.services.item]]
      icon = "icon-shuffle2"
      time = "8:00 PM"
      title = "Dancing"
      description = "Get down and boogie."
 
  [params.about]
    enable = true
    title = "Where"
    description = "2750 Adeline Drive<br>Burlingame, CA 94010"

    [[params.about.image]]
      img = "kohl_outside.png"
      title = "Kohl mansion facade"

    [[params.about.image]]
      img = "kohl_floor_plan.png"
      title = "Kohl mansion floorplan"

  [params.testimonials]
    enable = true
    title = "Answers"
    description = "Everything else you may wish to know."

    [[params.testimonials.item]]
      question = "What should I wear?"
      answer = "<b>Gentlemen:</b> a dark suit with an optional tie or bowtie and any kind of button up.<br><br><b>Ladies</b>: anything from over-the-knee sequined dresses to elegant ankle-length gowns."

    [[params.testimonials.item]]
      question = "Are you expecting a gift?"
      answer = 'No, thank you. Your presence is our present! But we also have an Amazon Wedding Registry <a href="https://smile.amazon.com/wedding/share/Diane-and-royce">here</a>.'
    
    [[params.testimonials.item]]
      question = "Is parking available?"
      answer = "Yes! It's free, and there is plenty of it, complete with handicap access."

    [[params.testimonials.item]]
      question = "How did you two meet?"
      answer = "We worked together in IT support at Google."
      
     [[params.testimonials.item]]
      question = "Can I have a centerpiece?"
      answer = "Yes! Take the candles, the flowers, board games, extra slices of cake..."
    
    [[params.testimonials.item]]
      question = "Who is in the wedding party?"
      answer = 'A combination of close family and friends; <a href="#who">complete list</a>'
      
     [[params.testimonials.item]]
      question = "Are children invited to your wedding?"
      answer = "Of course they are!  We wouldn't have it any other way."
      
     [[params.testimonials.item]]
      question = "How do I get there?"
      answer = 'There is no public transit to the mansion, but plenty of free parking (handicap access too): <a href="https://goo.gl/maps/BdwrbEXL2dq">map</a>'
     
     [[params.testimonials.item]]
      question = "What kind of entertainment or festivities will be there?"
      answer = "Board games, lawn games, music, and a dance floor."
      
     [[params.testimonials.item]]
      question = "Will there be drinks and food?"
      answer = 'Yes! We will have appetizers before the ceremony, an open bar, dinner, and a dessert bar. See the <a href="#menu">full menu here</a>'
      
     [[params.testimonials.item]]
      question = "Where are you going for your honeymoon?"
      answer = "Somewhere secret and romantic."
      
     [[params.testimonials.item]]
      question = "What can I do to help out with the wedding?"
      answer = "Show up! We would prefer that everyone relax and enjoy themselves. Our paid staff will take care of everything."
      
     [[params.testimonials.appetizer]]
      name = "Petite BBQ Pork Bun"
      contents = "scallion, sesame"
      
     [[params.testimonials.appetizer]]
      name = "Seared Beef Tenderloin"
      contents = "smoked potato, parmesan, sage contains dairy, gluten free"
      
     [[params.testimonials.appetizer]]
      name = "Mini Banh Mi"
      contents = "roast pork, pickled vegetables"
      
     [[params.testimonials.appetizer]]
      name = "Six Herb Crepes"
      contents = "Parma ham, roasted artichokes, shaved parmesan contains gluten, dairy"
      
     [[params.testimonials.appetizer]]
      name = "Celery Root Chip"
      contents = "fennel, goat cheese, black olive vegetarian. contains dairy"

     [[params.testimonials.dinner]]
       name = "Spring Asparagus Salad"
       contents = "poached asparagus with tarragon mustard vinaigrette, marinated beets, radishes and petite greens vegetarian. Contains gluten, dairy"

     [[params.testimonials.dinner]]
      name = "Tuscan Marinated Chicken Breast"
      contents = "roasted pepper, olives, fresh rosemary gluten free"

     [[params.testimonials.dinner]]
      name = "Seared Beef Tri Tip"
      contents = "rosemary oil, shaved Reggiano contains dairy, gluten free"

     [[params.testimonials.dinner]]
      name = "Artichoke and and Goat Cheese Strudel"
      contents = "balsamic balsamic syrup syrup vegetarian, vegetarian, contains contains gluten, gluten, dairy dairy"

     [[params.testimonials.dinner]]
      name = "Summer French Beans"
      contents = "shallots, thyme, tomato gluten free, vegan"

     [[params.testimonials.dinner]]
      name = "Artisan Breads"
      contents = "a seasonal selection Straus dairy cultured organic butter contains gluten, dairy"

     [[params.testimonials.dessert]]
      name = "Passion Curd Tart"
      contents = "vegan. contains gluten"

     [[params.testimonials.dessert]]
      name = "Huckleberry Breton Cookie"
      contents = "contains gluten, dairy"

     [[params.testimonials.dessert]]
      name = "Strawberry Mascarpone Panna Cotta"
      contents = "gluten free. contains gelatin"

     [[params.testimonials.dessert]]
      name = "Milk Chocolate Cherry Cheesecake"
      contents = "contains gluten, dairy"

     [[params.testimonials.beverage]]
     name = "Coffee / Tea"
     contents = "Ask server for options."

     [[params.testimonials.beverage]]
     name = "White"
     contents = "Greywacke SauvignonBlanc 2016<br/>Sonoma-CutrerRussianRiver Chardonnay 2015<br>Domaine Carneros Brut"

     [[params.testimonials.beverage]]
     name = "Red"
     contents = "Dept C Pinot Noir AndersonValley 2012<br/>Whitehall Lane Tre Leoni Cabernet Blend 2014"

     [[params.testimonials.beverage]]
     name = "Beer"
     contents = "Anchor California Lager<br/> Racer 5 IPA<br/>Amstel Light"

      
  [params.contact]
    enable = true
    title = "Who"
    description = "Members of the wedding party."

    [[params.contact.one]]
      name = "Diane Tran"
      position = "Bride"
      img = "diane_tran.jpg"
      social = [
        ["icon-facebook", "https://www.facebook.com/dammmitdiane"],
        ["icon-linkedin", "https://www.linkedin.com/in/dianediemtran"]
      ]

    [[params.contact.one]]
      name = "Royce Remer"
      position = "Groom"
      img = "royce_remer.jpg"
      social = [
        ["icon-facebook", "https://www.facebook.com/royceremer"],
        ["icon-linkedin", "https://www.linkedin.com/in/royceremer"]
      ]

    [[params.contact.two]]
      name = "Jillian Middleton"
      position = "Maid of Honor"
      img = "jillian.JPG"
      relation = "Best friend from college."
      social = [
        ["icon-facebook", "https://www.facebook.com/itsjillianmcl"],
      ]

    [[params.contact.two]]
      name = "Rochelle Chantengco"
      position = "Bridesmaid"
      img = "rochelle.jpg"
      relation = "Childhood friend."
      social = [
        ["icon-facebook", "https://www.facebook.com/rochellechan"],
      ]

    [[params.contact.two]]
      name = "James O'Hanrahan"
      position = "Man of Honor"
      img = "james_ohanrahan.jpg"
      relation = "2nd cousin and childhood friend."
      social = [
        ["icon-facebook", "https://www.facebook.com/james.ohanrahan"],
      ]

    [[params.contact.two]]
      name = "Evan Gerardo"
      position = "Groomsman"
      img = "person2.jpg"
      relation = "Unofficial 3rd brother and childhood friend."
      social = [
        ["icon-home", "https://evangerardo.com"]
      ]

    [[params.contact.three]]
      name = "Shilpi Tomar"
      position = "Bridesmaid"
      img = "shilpi.jpg"
      relation = "College friend from SJSU."
      social = [
        ["icon-facebook", "https://www.facebook.com/shilpi.tomar"],
      ]

    [[params.contact.three]]
      name = "Jerome Chen"
      position = "Bridesman"
      img = "jerome.png"
      relation = "Longtime coworker and prior roommate."
      social = []

    [[params.contact.three]]
      name = "Norman Remer"
      position = "Groomsman"
      img = "norman_remer.jpg"
      relation = "Eldest brother."
      social = []

    [[params.contact.three]]
      name = "Patrick Remer"
      position = "Groomsman"
      img = "patrick_remer.jpg"
      relation = "Elder brother."
      social = [
        ["icon-facebook", "https://www.facebook.com/patrick.remer.98"],
      ]

    [[params.contact.four]]
      name = "Emilio Arias"
      position = "Officiant"
      img = "emilio_arias.jpg"
      relation = "Prior roommate."
      social = [
        ["icon-facebook", "https://www.facebook.com/emilio.arias"],
      ]

    [[params.contact.four]]
      name = "Colleen Bataille"
      position = "Planner"
      img = "colleen_bataille.png"
      relation = "Planned Jillian's wedding!"
      social = [
        ["icon-facebook", "https://www.facebook.com/inspiredeventsbycb33"],
        ["icon-instagram", "http://instagram.com/inspiredeventsbycb"],
        ["icon-pinterest", "https://www.pinterest.com/inspiredevents3"],
        ["icon-home", "https://www.inspiredeventsbycb.com"]
      ]
      
    [[params.contact.four]]
      name = "Heather Elizabeth"
      position = "Photographer"
      img = "heatherelizabeth.jpg"
      relation = "Photographed Christy and Jason's wedding!"
      social = [
        ["icon-facebook", "https://www.facebook.com/heatherelizabethphotography"],
        ["icon-instagram", "https://www.instagram.com/theheatherelizabeth"],
        ["icon-pinterest", "https://www.pinterest.com/heatherelizs"],
        ["icon-home", "https://heatherelizabethphotography.com"]
      ]
