baseURL = "https://dianeandroyce.com/"
languageCode = "en-us"
title = "Diane to be a Remer"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/colors.css","css/header.css","css/home.css","css/when.css","css/answers.css","css/where.css"]
  
  [params.navigation]
    brand = "#DianeToBeARemer"
    services = "when"
    about = "where"
    testimonials = "answers"
    contact = "who"

  [params.hero]
    title = "Diane to be a Remer!"
    subtitle = 'A union of <a ref="#diane" target="_blank">Diane Tran</a> and <a ref="#royce" target="_blank">Royce Remer</a>'
 
  [params.services]
    enable = true
    title = "When"
    date = "June 28th, 2019"

    [[params.services.item]]
      icon = "icon-bell2"
      time = "3:15 PM"
      title = "Ceremony"
      description = "A short procession and witnessing of our vows."

    [[params.services.item]]
      icon = "icon-camera2"
      time = "4:00 PM"
      title = "Photos"
      description = 'All the permutations of guest photos. Games and drinks too.'

    [[params.services.item]]
      icon = "icon-moon2"
      time = "5:45 PM"
      title = "Dinner"
      description = 'Dinner is served. <a ref="#menu" target="_blank">Menu here</a>.'

    [[params.services.item]]
      icon = "icon-microphone"
      time = "6:00 PM"
      title = "Toasts"
      description = "People extol Dian's grace and fine taste."

    [[params.services.item]]
      icon = "icon-pie-graph"
      time = "7:30 PM"
      title = "Cake"
      description = "People take bites out of Diane's cake."

    [[params.services.item]]
      icon = "icon-shuffle2"
      time = "8:00 PM"
      title = "Dancing"
      description = "Get down and boogie."
 
  [params.about]
    enable = true
    title = "Where"
    description = "2750 Adeline Drive<br>Burlingame, CA 94010"

  [params.testimonials]
    enable = true
    title = "Answers"
    description = "Everything else you may wish to know."

    [[params.testimonials.item]]
      question = "What should I wear?"
      answer = "<b>Gentlemen:</b> a dark suit with an optional tie or bowtie and any kind of button up.<br><br><b>Ladies</b>: anything from over-the-knee sequined dresses to elegant ankle-length gowns."
      person = "Mr. Badger"
      img = "mrbadger.png"
      alt = "Mr. Badger"

    [[params.testimonials.item]]
      question = "Are you expecting a gift?"
      answer = "No, thank you.  Your presence is our present! If you absolutely insist on giving a gift, refer to <a href=registries.md>registries here</a>"
    
    [[params.testimonials.item]]
      question = "Is parking available?"
      answer = "Yes! It's free, and there is plenty of it, complete with handicap access."

    [[params.testimonials.item]]
      question = "How did you two meet?"
      answer = "We both worked in a Tech Stop at Google and sat next to each other.  We were an efficient team with complementary skillsets; Royce was far more technical when working with engineers and Diane was much more patient with the non-technical folks."
    
    [[params.testimonials.item]]
      question = "Who is in the wedding party?"
      answer = 'A combination of close family and friends; <a ref="#who" target="_blank">complete list</a>'
      
     [[params.testimonials.item]]
      question = "Are children invited to your wedding?"
      answer = "Of course they are!  We wouldn't have it any other way."
      
     [[params.testimonials.item]]
      question = "How do I get there?"
      answer = "We have all the information you need on the (link here) page!"
     
     [[params.testimonials.item]]
      question = "What kind of entertainment or festivities will be there?"
      answer = "Board games, lawn games, music, and a dance floor."
      
     [[params.testimonials.item]]
      question = "Will there be drinks and food?"
      answer = "Yes! We will have hors d'oeuvres before the ceremony, an open bar, dinner, and a dessert bar."
      
     [[params.testimonials.item]]
      question = "Where are you going for your honeymoon?"
      answer = "Somewhere secret and romantic."
      
     [[params.testimonials.item]]
      question = "What can I do to help out with the wedding?"
      answer = "Show up! We would prefer that everyone relax and enjoy themselves. Our paid staff will take care of everything."
      
      
  [params.contact]
    enable = true
    title = "Who"
    description = "Members of the wedding party."

    [[params.contact.hers]]
      name = "Diane Tran"
      position = "Bride"
      description = ""
      img = "person1.jpg"
      social = [
        ["icon-facebook", "https://www.facebook.com/dammmitdiane"],
        ["icon-linkedin", "https://www.linkedin.com/in/dianediemtran"]
      ]

    [[params.contact.his]]
      name = "Royce Remer"
      position = "Groom"
      description = ""
      img = "person1.jpg"
      social = [
        ["icon-facebook", "https://www.facebook.com/royceremer"],
        ["icon-linkedin", "https://www.linkedin.com/in/royceremer"]
      ]

    [[params.contact.theirs]]
      name = "Colleen Bataille"
      position = "Planner"
      description = ""
      img = "person1.jpg"
      social = [
        ["icon-facebook", "https://www.facebook.com/inspiredeventsbycb33"],
        ["icon-linkedin", "https://www.linkedin.com/in/colleen-bataille"],
        ["icon-instagram", "http://instagram.com/inspiredeventsbycb"],
        ["icon-pinterest", "https://www.pinterest.com/inspiredevents3"],
        ["icon-home", "https://www.inspiredeventsbycb.com"]
      ]
